(()=>{'use strict';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],clamp=x=>Math.max(0,Math.min(1,x)),smooth=(a,b,x)=>{x=clamp((x-a)/(b-a));return x*x*(3-2*x)};
const menu=$('#menu'),open=$('#menu-open'),close=$('#menu-close'),mq=matchMedia('(prefers-reduced-motion: reduce)');let paused=mq.matches,lang=document.documentElement.lang==='en'?'en':'de';const PATHS={de:'/gefängnisplanet/',en:'/prisonplanet/'};const copy=all('[data-en]').map(e=>[e,e.innerHTML]);
window.GP={paused,lang,progress:0,cosmos:0,pointer:{x:0,y:0},clamp,smooth};
function openMenu(){menu.showModal();document.body.classList.add('locked');open.setAttribute('aria-expanded','true');close.focus();window.dispatchEvent(new Event('gp-wake'))}function closeMenu(){menu.close()}
menu.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const focusable=[...menu.querySelectorAll('button,a[href]')].filter(el=>el.getClientRects().length);const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
open.addEventListener('click',openMenu);close.addEventListener('click',closeMenu);menu.addEventListener('close',()=>{document.body.classList.remove('locked');open.setAttribute('aria-expanded','false');open.focus();window.dispatchEvent(new Event('gp-wake'))});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{closeMenu();setTimeout(()=>{const t=$(a.hash);t.setAttribute('tabindex','-1');t.focus({preventScroll:true})},450)}));
function motion(){GP.paused=paused;document.body.classList.toggle('reduced',paused);$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').setAttribute('aria-label',lang==='de'?(paused?'Bewegung fortsetzen':'Bewegung pausieren'):(paused?'Resume motion':'Pause motion'));$('.motion-symbol').textContent=paused?'▷':'Ⅱ';update();window.dispatchEvent(new Event('gp-wake'))}$('#motion').addEventListener('click',()=>{paused=!paused;motion()});mq.addEventListener('change',e=>{paused=e.matches;motion()});
// One address per language, so booting into English is the same code path
// as switching by hand - and switching by hand keeps the address honest.
function applyLang(){GP.lang=lang;document.documentElement.lang=lang;copy.forEach(([e,de])=>e.innerHTML=lang==='de'?de:e.dataset.en.replace(/\\n/g,'<br>'));$('#language').textContent=lang==='de'?'EN':'DE';$('#language').setAttribute('aria-label',lang==='de'?'Switch to English':'Zu Deutsch wechseln');motion()}
$('#language').addEventListener('click',()=>{lang=lang==='de'?'en':'de';applyLang();if(location.protocol.startsWith('http'))try{history.replaceState(null,'',PATHS[lang]+location.hash)}catch{}});
const object=$('#start'),cosmos=$('#horizont'),hero=$('.hero-type'),one=$('.scene-copy-one'),two=$('.scene-copy-two'),caption=$('.object-caption'),lines=all('.orbit-line');let queued=false;
function progress(e){const r=e.getBoundingClientRect();return clamp(-r.top/Math.max(1,r.height-innerHeight))}
function update(){queued=false;const p=paused?0:progress(object),c=paused?0:progress(cosmos);GP.progress=p;GP.cosmos=c;const h=smooth(.04,.24,p);hero.style.opacity=1-h;hero.style.transform=`translate(-50%,${-h*130}px)`;one.style.opacity=smooth(.18,.30,p)*(1-smooth(.53,.65,p));one.style.transform=`translateX(${(1-smooth(.18,.32,p))*-60}px)`;two.style.opacity=smooth(.63,.78,p);two.style.transform=`translateX(${(1-smooth(.63,.78,p))*60}px)`;caption.style.opacity=1-smooth(.1,.25,p);lines.forEach((e,i)=>e.style.opacity=1-smooth(.14,.34,p));$('.scene-track i').style.transform=`scaleX(${Math.max(.025,p)})`;$('#scene-label').textContent=lang==='de'?(p<.2?'01 / ANKOMMEN':p<.63?'02 / BLICKWECHSEL':'03 / IM RAUM'):(p<.2?'01 / ARRIVAL':p<.63?'02 / THE GAZE':'03 / IN SPACE');$('.cosmos-title').style.opacity=1-smooth(.13,.39,c);$('.cosmos-title').style.transform=`translateX(${-smooth(.1,.45,c)*110}px)`;$('.cosmos-note').style.opacity=smooth(.50,.75,c);$('.cosmos-note').style.transform=`translateY(${(1-smooth(.5,.75,c))*45}px)`;$('.cosmos-progress i').style.transform=`scaleX(${c})`;
if(!paused){all('.reading-card').forEach((el,i,arr)=>{const next=arr[i+1];const cover=next?smooth(innerHeight*.85,125, next.getBoundingClientRect().top):0;el.style.scale=String(1-cover*.035);el.style.filter=`brightness(${1-cover*.08})`})}else all('.reading-card').forEach(el=>{el.style.scale='1';el.style.filter='none'});const tri=$('#trilogie'),tp=paused?0:progress(tri);$('.trilogy-track').style.transform=paused?'none':`translate3d(${-tp*200/3}%,0,0)`;all('[data-chapter]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===Math.round(tp*2))));window.dispatchEvent(new Event('gp-frame'));}
all('[data-chapter]').forEach(b=>b.addEventListener('click',()=>{const tri=$('#trilogie');if(paused){tri.querySelectorAll('.trilogy-panel')[+b.dataset.chapter].scrollIntoView({behavior:'auto'})}else window.scrollTo({top:tri.offsetTop+(tri.offsetHeight-innerHeight)*(+b.dataset.chapter/2),behavior:'smooth'})}));
function request(){if(!queued){queued=true;requestAnimationFrame(update)}}window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',request,{passive:true});document.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){GP.pointer.x=e.clientX/innerWidth*2-1;GP.pointer.y=e.clientY/innerHeight*2-1;window.dispatchEvent(new Event('gp-wake'))}},{passive:true});applyLang();
})();
