(()=>{'use strict';const $=s=>document.querySelector(s),clamp=GP.clamp,sm=GP.smooth;
let objectVisible=false,cosmosVisible=false,raf=0,last=0,time=0,settle=0,renderer,scene,camera,root,eye,orbLight,cr,cs,cc,cm,angleExtra=0,closeExtra=0,dragAngle=0,dragPitch=0,resetGaze=false,frames=0,renderCost=0,quality=1;
let yaw=0,pitch=0,eyeYaw=0,eyePitch=0,px=0,py=0,scale=1,cosAngle=.3,cosOrbit=0,cosDistance=8.2;
function unpack(e){let bytes=Uint8Array.from(atob(e.d),c=>c.charCodeAt(0)),v=new Uint16Array(bytes.buffer,0,e.nv*3),p=new Float32Array(e.nv*3);for(let i=0;i<p.length;i++)p[i]=v[i]*e.sc[i%3]+e.lo[i%3];let f=new Uint16Array(bytes.buffer,e.nv*6,e.nf*3),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setIndex(new THREE.BufferAttribute(f,1));g.computeVertexNormals();return g}
function initEye(){if(renderer)return;try{if(!window.THREE||!window.EYE_MODEL)throw Error('Model unavailable');renderer=new THREE.WebGLRenderer({canvas:$('#eye-canvas'),alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;scene=new THREE.Scene();camera=new THREE.OrthographicCamera(-2,2,2,-2,.01,30);camera.position.set(0,0,6);camera.lookAt(0,0,0);root=new THREE.Group();scene.add(root);eye=new THREE.Group();eye.position.z=-.3;root.add(eye);
const stone=new THREE.MeshStandardMaterial({color:0x858775,roughness:.91,metalness:0});stone.onBeforeCompile=s=>{s.vertexShader='varying vec3 stonePos;\n'+s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nstonePos=position;');s.fragmentShader=`varying vec3 stonePos;
float stoneHash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
float grain(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(stoneHash(i),stoneHash(i+vec3(1,0,0)),f.x),mix(stoneHash(i+vec3(0,1,0)),stoneHash(i+vec3(1,1,0)),f.x),f.y),mix(mix(stoneHash(i+vec3(0,0,1)),stoneHash(i+vec3(1,0,1)),f.x),mix(stoneHash(i+vec3(0,1,1)),stoneHash(i+vec3(1,1,1)),f.x),f.y),f.z);}
`+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float rock=grain(stonePos*18.)*.55+grain(stonePos*90.)*.28+grain(stonePos*310.)*.17;float vein=pow(abs(sin(stonePos.y*8.+stonePos.x*3.+grain(stonePos*4.)*3.)),24.);diffuseColor.rgb*=.68+rock*.5-vein*.085;`);};
const lightMaterial=new THREE.MeshStandardMaterial({color:0x9ccc09,emissive:0x98f500,emissiveIntensity:.95,roughness:.3,metalness:.05});lightMaterial.onBeforeCompile=s=>{s.vertexShader='varying vec3 gazePos;\n'+s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ngazePos=position;');s.fragmentShader='varying vec3 gazePos;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float radial=length(gazePos.xy);float pupil=smoothstep(.10,.108,radial);diffuseColor.rgb=mix(vec3(.006,.014,.005),diffuseColor.rgb,pupil);`);s.fragmentShader=s.fragmentShader.replace('#include <emissivemap_fragment>',`#include <emissivemap_fragment>
totalEmissiveRadiance*=smoothstep(.102,.110,length(gazePos.xy))*(.65+.35*smoothstep(.1,.36,length(gazePos.xy)));`)};
const interior=new THREE.MeshStandardMaterial({color:0x25291f,roughness:1});
EYE_MODEL.forEach(e=>{const g=unpack(e),moving=e.n===27||e.n===28;if(moving)g.translate(0,0,.3);const mesh=new THREE.Mesh(g,e.n===27?lightMaterial:[23,28].includes(e.n)?interior:stone);(moving?eye:root).add(mesh)});
scene.add(new THREE.HemisphereLight(0xf6f6e9,0x373c31,.50));const key=new THREE.DirectionalLight(0xfff6df,1.55);key.position.set(-3,4,5);scene.add(key);const fill=new THREE.DirectionalLight(0xd5e6e4,.36);fill.position.set(4,0,3);scene.add(fill);const rim=new THREE.DirectionalLight(0xffffff,1.1);rim.position.set(1,3,-3);scene.add(rim);orbLight=new THREE.PointLight(0xc9ff41,.2,1.5,2);orbLight.position.set(0,0,.28);root.add(orbLight);$('#eye-canvas').dataset.ready='true';resizeEye();}catch(e){$('#eye-canvas').hidden=true;$('.eye-fallback').hidden=false;console.warn('Eye fallback',e.message)}}
function resizeEye(){if(!renderer)return;const el=$('.object-sticky'),w=el.clientWidth,h=el.clientHeight,aspect=w/h,mobile=w<761,half=mobile?1.0/aspect:1.4;renderer.setSize(w,h,false);camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();wake()}
function drawEye(dt){if(!renderer)return;const p=GP.progress,mobile=innerWidth<761,a=sm(.12,.45,p),b=sm(.55,1,p);let ty=.02-a*.35+b*1.2+dragAngle,tx=.05+a*.13-b*.34+dragPitch;let x=mobile?0:a*.60-b*1.28,y=mobile?-.50+a*1.16-b*.02:-.46+a*.4-b*.08;let z=mobile?1.01-a*.25-b*.01:.93-a*.13+b*.05;const speed=GP.paused?1:1-Math.exp(-dt*8);yaw+=(ty-yaw)*speed;pitch+=(tx-pitch)*speed;px+=(x-px)*speed;py+=(y-py)*speed;scale+=(z-scale)*speed;root.rotation.set(pitch,yaw,-.06+b*.08);root.position.set(px,py,0);root.scale.setScalar(scale);
let gaze=GP.paused||resetGaze?0:Math.sin(p*10)*.30+GP.pointer.x*.13,up=GP.paused||resetGaze?0:Math.sin(p*7+.1)*.12-GP.pointer.y*.1;eyeYaw+=(gaze-eyeYaw)*speed;eyePitch+=(up-eyePitch)*speed;eye.rotation.set(eyePitch,eyeYaw,0);orbLight.intensity=.18+(GP.paused?0:.035*Math.sin(time*.6));renderer.render(scene,camera);}

const fragment=`precision highp float;
uniform vec2 resolution;uniform float time;uniform float incline;uniform float orbit;uniform float distance;uniform float bending;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=noise(p)*a;p=p*2.03+8.9;a*=.5;}return v;}
vec3 stars(vec3 ray){vec2 uv=vec2(atan(ray.z,ray.x),asin(clamp(ray.y,-1.,1.)));vec3 col=vec3(.0015,.003,.0055);float cloud=fbm(uv*3.5+7.);col+=vec3(.018,.023,.031)*pow(cloud,4.)*2.;for(int i=0;i<2;i++){float scale=160.+float(i)*107.;vec2 cell=uv*scale;vec2 id=floor(cell),f=fract(cell);float r=hash(id+float(i)*12.);float spot=length(f-vec2(hash(id+3.1),hash(id+4.9)));float star=smoothstep(.055,.0,spot)*step(.988,r);col+=mix(vec3(.46,.59,.75),vec3(.9,.8,.58),r)*star*(.4+hash(id+11.));}return col;}
vec3 disk(vec3 p){float r=length(p.xz);float phi=atan(p.z,p.x);float flow=phi-time*.27/pow(r,.8);float f=fbm(vec2(r*3.9,flow*5.));float ring=.5+.5*sin(r*92.+f*9.+sin(flow*15.)*.5);float fine=.6+.4*sin(r*217.+flow*4.);float tex=.33+.55*f+.3*ring*fine;float inner=smoothstep(1.62,1.95,r);float outer=exp(-max(r-2.,0.)*.58)*(1.-smoothstep(4.1,5.8,r));float hot=pow(2./max(r,1.7),1.5);float doppler=pow(clamp(1.+p.x/r*.4,.3,1.7),2.);vec3 color=mix(vec3(.40,.15,.035),vec3(1.1,.74,.36),clamp(hot-.1,0.,1.));color=mix(color,vec3(1.2,1.05,.85),smoothstep(.86,1.2,hot));return color*tex*hot*inner*outer*doppler*2.4;}
void main(){vec2 uv=(gl_FragCoord.xy-.5*resolution)/resolution.y;uv.y+=.02;float a=.12+incline*.53;vec3 ro=vec3(sin(orbit)*cos(a),sin(a),cos(orbit)*cos(a))*distance;vec3 forward=normalize(-ro),right=normalize(cross(forward,vec3(0,1,0))),up=cross(right,forward);float fit=min(1.,resolution.x/resolution.y*.88);vec3 rd=normalize(forward+right*uv.x*1.20/fit+up*uv.y*1.20/fit);vec3 p=ro,v=rd;float h2=dot(cross(p,v),cross(p,v));vec3 col=vec3(0);float transmission=1.;bool captured=false;
 for(int i=0;i<112;i++){float r=length(p);if(r<.66){captured=true;break;}if(r>19.)break;float stepSize=clamp(r*.09,.045,.36);vec3 old=p;vec3 acc=-1.5*.66*h2*p/pow(r,5.)*bending;v+=acc*stepSize;p+=v*stepSize;
 if(old.y*p.y<0.){float t=old.y/(old.y-p.y);vec3 hit=mix(old,p,t);float radius=length(hit.xz);if(radius>1.64&&radius<5.8){vec3 emitted=disk(hit);col+=transmission*emitted;transmission*=.18;}}
 }
 if(!captured)col+=stars(normalize(v))*transmission;
 col=vec3(1.)-exp(-col*1.8);col=pow(col,vec3(.4545));float vignette=1.-.3*smoothstep(.35,1.1,length(uv));col*=vignette;gl_FragColor=vec4(col,1.);
}`;
function initCosmos(){if(cr)return;try{cr=new THREE.WebGLRenderer({canvas:$('#cosmos-canvas'),antialias:false,powerPreference:'low-power'});cr.setPixelRatio(Math.min(devicePixelRatio,innerWidth<761?1:1.15));cs=new THREE.Scene();cc=new THREE.Camera();cm=new THREE.ShaderMaterial({uniforms:{resolution:{value:new THREE.Vector2()},time:{value:0},incline:{value:.3},orbit:{value:0},distance:{value:8.2},bending:{value:1}},vertexShader:'void main(){gl_Position=vec4(position,1.);}',fragmentShader:fragment,depthWrite:false,depthTest:false});cs.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),cm));$('#cosmos-canvas').dataset.ready='true';resizeCosmos()}catch(e){$('#cosmos-canvas').hidden=true;$('.cosmos-fallback').hidden=false;console.warn('Cosmos fallback',e.message)}}
function resizeCosmos(){if(!cr)return;const e=$('.cosmos-sticky');cr.setSize(e.clientWidth,e.clientHeight,false);cr.getDrawingBufferSize(cm.uniforms.resolution.value);wake()}
function drawCosmos(dt){if(!cr)return;const c=GP.cosmos,k=GP.paused?1:1-Math.exp(-dt*5);cosAngle+=(.16+sm(.12,.78,c)*1.12+angleExtra-cosAngle)*k;cosOrbit+=(-.15+c*1.1+GP.pointer.x*.1-cosOrbit)*k;cosDistance+=(8.9-sm(.25,.9,c)*2.6-closeExtra-cosDistance)*k;cm.uniforms.time.value=time;cm.uniforms.incline.value=cosAngle;cm.uniforms.orbit.value=cosOrbit;cm.uniforms.distance.value=cosDistance;cr.render(cs,cc)}
function wake(){settle=performance.now()+1100;if(!raf&&!document.hidden&&(objectVisible||cosmosVisible)&&!$('#menu').open)raf=requestAnimationFrame(frame)}
function frame(now){raf=0;if(document.hidden||$('#menu').open)return;if(cosmosVisible&&innerWidth<761&&!GP.paused&&now-last<30){raf=requestAnimationFrame(frame);return}const dt=Math.min((now-last)/1000||.016,.05);last=now;if(!GP.paused)time+=dt;const start=performance.now();if(objectVisible)drawEye(dt);if(cosmosVisible)drawCosmos(dt);frames++;renderCost+=(performance.now()-start);if(frames%90===0&&cr&&cosmosVisible){if(renderCost/frames>18&&quality===1){quality=.7;cr.setPixelRatio(.75);resizeCosmos()}}
if((cosmosVisible&&!GP.paused)||((objectVisible||cosmosVisible)&&now<settle))raf=requestAnimationFrame(frame)}
const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.target.id==='start'){objectVisible=e.isIntersecting;if(objectVisible)initEye()}else{cosmosVisible=e.isIntersecting;if(cosmosVisible)initCosmos()}});wake()},{threshold:0});io.observe($('#start'));io.observe($('#horizont'));new ResizeObserver(resizeEye).observe($('.object-sticky'));new ResizeObserver(resizeCosmos).observe($('.cosmos-sticky'));window.addEventListener('gp-frame',()=>{resetGaze=false;wake()});window.addEventListener('gp-wake',wake);document.addEventListener('visibilitychange',()=>{last=performance.now();if(!document.hidden)wake()});
$('#orbit').addEventListener('click',e=>{angleExtra=angleExtra===0?.65:0;e.currentTarget.setAttribute('aria-pressed',String(angleExtra!==0));wake()});$('#approach').addEventListener('click',e=>{closeExtra=closeExtra===0?1.9:0;e.currentTarget.setAttribute('aria-pressed',String(closeExtra!==0));wake()});$('#eye-reset').addEventListener('click',()=>{dragAngle=dragPitch=0;resetGaze=true;wake()});
for(const id of ['eye-canvas','cosmos-canvas']){const el=$('#'+id);let pointer=null;el.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,id:e.pointerId};if(e.pointerType==='mouse')el.setPointerCapture(e.pointerId);if(e.pointerType==='touch'){GP.pointer.x=e.clientX/innerWidth*2-1;GP.pointer.y=e.clientY/innerHeight*2-1;wake()}},{passive:true});el.addEventListener('pointermove',e=>{if(!pointer||e.pointerType==='touch')return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(id==='eye-canvas'){dragAngle+=dx*.004;dragPitch=Math.max(-.4,Math.min(.4,dragPitch+dy*.002))}else{angleExtra=Math.max(-.1,Math.min(.9,angleExtra+dy*.003));GP.pointer.x+=dx*.002}pointer={x:e.clientX,y:e.clientY};wake()},{passive:true});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>el.addEventListener(ev,()=>pointer=null));el.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(id==='eye-canvas'){if(e.key==='ArrowLeft')dragAngle-=.15;if(e.key==='ArrowRight')dragAngle+=.15;if(e.key==='ArrowUp')dragPitch-=.1;if(e.key==='ArrowDown')dragPitch+=.1;if(e.key==='Home')dragAngle=dragPitch=0}else{if(e.key==='ArrowUp')angleExtra+=.15;if(e.key==='ArrowDown')angleExtra-=.15;if(e.key==='ArrowLeft')GP.pointer.x-=.4;if(e.key==='ArrowRight')GP.pointer.x+=.4;if(e.key==='Home'){angleExtra=0;closeExtra=0}}wake()});el.addEventListener('webglcontextlost',e=>{e.preventDefault();el.hidden=true;$(id==='eye-canvas'?'.eye-fallback':'.cosmos-fallback').hidden=false});}
window.GP.sceneState=()=>({eyeReady:!!renderer,cosmosReady:!!cr,objectVisible,cosmosVisible,paused:GP.paused,progress:GP.progress,cosmosProgress:GP.cosmos,yaw,eyeYaw,eyePitch,cosAngle,cosDistance,frames,quality,triangles:renderer?.info.render.triangles,drawCalls:renderer?.info.render.calls});
})();
